# Generated by Django 5.2.4 on 2025-08-12 04:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0003_group_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('expense_created', 'Expense Created'), ('expense_updated', 'Expense Updated'), ('expense_deleted', 'Expense Deleted'), ('settlement_created', 'Settlement Created'), ('settlement_confirmed', 'Settlement Confirmed'), ('settlement_rejected', 'Settlement Rejected'), ('member_joined', 'Member Joined'), ('member_left', 'Member Left'), ('member_added', 'Member Added'), ('member_removed', 'Member Removed'), ('group_created', 'Group Created'), ('group_updated', 'Group Updated')], max_length=30)),
                ('description', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='groups.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Activities',
                'ordering': ['-created_at'],
            },
        ),
    ]
